### ISSUE TITLE
[Feature Request] Import wish history from Paimon.moe

### ISSUE THREAD

**Issue by ignaciocastro** [seriaati/shenhe_bot#371]
Paimon.moe exports wish history in .xlsx, following this format:

![image](https://user-images.githubusercontent.com/7141944/200195651-aa8956e0-fb86-402b-b093-fd3093164554.png)

Could it be possible to use this exported file to import into Shenhe? Considering people who have their full wish history saved on paimon.moe since it already expired on Genshin's official link. That way those users will be able to have their full history on Shenhe as well.

I can provide a sample file if necessary.

**Comment by seriaati** [comment]
I have implemented this feature in https://github.com/seriaati/shenhe_bot/commit/d06ab9dff2adbc3806a302bac975492ebddce350
However, I have made it in a [separate branch](https://github.com/seriaati/shenhe_bot/pull/372) instead of the main branch.

This is because the wishes exported from paimon.moe are missing a key data - the wish's ID.
Without the ID, it is impossible the distinguish whether the wish is unique or not; for example, you may pull two same weapons in a single 10-pull, and it's impossible to distinguish between them from just the item's name and pull time. 
This means that there is a risk of saving duplicate wishes in the database.

I have joined the paimon.moe Discord server and DMed its developer regarding this information.
If they are willing to provide wish IDs in paimon.moe's excel file, then I can just add it and merge the branch, then the feature will be implemented in the Shenhe you're using right now.
If not, then I'm sorry, but this feature won't be able to be implemented.
